development:
  adapter: mysql2
  database: sample_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: sample_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: sample_production
  username: root
  password:
  host: localhost

users:
  adapter: mysql2
  database: users
  username: root
  password:
  host: localhost
